# 决定哪些 sources/*.txt 拼成哪个 dist/*.yaml
# name: 产物文件名（dist/<name>.yaml）
# sources: 相对 sources/ 的路径列表

outputs:
  - name: Dev-Media
    sources:
      - dev-media.txt

  - name: Steam-Epic-Download
    sources:
      - steam-epic-download.txt

  - name: Steam
    sources:
      - steam.txt

  - name: Microsoft
    sources:
      - microsoft.txt

  - name: Bypass-AD
    sources:
      - bypass-ad.txt
